services:
  - type: web
    name: cryocorp-whatsapp-ai-bot
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
    startCommand: node index.js
    envVars:
      - key: CHROME_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: NODE_ENV
        value: production
